# Pandas

In [11]:
import pandas as pd
pd.__version__
print(pd.__version__)

2.3.3

In [12]:
import pandas as pd

names = ['Amit ', 'raghav', 'rahul', 'Anil ','anoop','putna','Kansika']
s = pd.Series(names)
print(s)

0      Amit
1     raghav
2      rahul
3      Anil
4      anoop
5      putna
6    Kansika
dtype: object

In [14]:
import pandas as pd

credits = [10,20,30,50]
s = pd.Series(credits,index =['Maths','Phyiscs', 'Chemistry','English'])
print(s)

Maths        10
Phyiscs      20
Chemistry    30
English      50
dtype: int64

In [20]:
list = ['banana','Apple','Orange','Mango']
print(pd.Series(list,index=[5,12,15,23]))

5     banana
12     Apple
15    Orange
23     Mango
dtype: object

In [23]:
std_info = {
    'Name' : 'Aman',
    'Country': 'India', 
    'City ': 'Gorakhpur'
}
print(pd.Series(std_info))

Name            Aman
Country        India
City       Gorakhpur
dtype: object

In [30]:
my_info ={
    'Name': ['Harshit','alien','kansika'],
    'City':['Shahjahanpur','kanpur','Naubasta'],
    'Country': ['Kanpur','kannauj','america'],
    'Age': ['24','35','60']
}
print(pd.Series(my_info))

Name              [Harshit, alien, kansika]
City       [Shahjahanpur, kanpur, Naubasta]
Country          [Kanpur, kannauj, america]
Age                            [24, 35, 60]
dtype: object

In [32]:
s =pd.Series(10,index=[1,2,3])
s

1    10
2    10
3    10
dtype: int64

In [37]:
import numpy as np

s= pd.Series(np.linspace(5,10,5))
s

0     5.00
1     6.25
2     7.50
3     8.75
4    10.00
dtype: float64

In [42]:
# Dataframe uses in 2d data
data =  { 'Name': ['Harshit','alien','kansika'],
    'City':['Berlin','Null','Naubasta'],
    'Country': ['Germany','Greenland','America'],
    'Age': ['24','35','60'] }
df = pd.DataFrame(data)
df

      Name      City    Country Age
0  Harshit    Berlin    Germany  24
1    alien      Null  Greenland  35
2  kansika  Naubasta    America  60

In [43]:
data =  [ ['Harshit','alien','kansika'],
           ['Berlin','Null','Naubasta'],
           ['Germany','Greenland','America'],
            ['24','35','60'] ]
df = pd.DataFrame(data,columns=['Name','Country','Age'])
df

      Name    Country       Age
0  Harshit      alien   kansika
1   Berlin       Null  Naubasta
2  Germany  Greenland   America
3       24         35        60

In [ ]:
data =  [['Harshit','alien','kansika'],
         ['Berlin','Null','Naubasta'],
         ['Germany','Greenland','America'],
         ['24','35','60'] ]
df = pd.DataFrame(data,
                    columns=['Name','Country','Age'],
                    index=['person1','person2','person3','person4']
                    )

df

            Name    Country       Age
person1  Harshit      alien   kansika
person2   Berlin       Null  Naubasta
person3  Germany  Greenland   America
person4       24         35        60

In [ ]:
# Dataframe uses in 2d data
data =  {
    'Joe':[10,24,35,],
     'harry':[20.00],
     'Patlu':[24.4]   
}

df = pd.DataFrame(data.items(),columns =['Name','Marks'])
df

    Name   Marks
0    Joe    [10]
1  harry  [20.0]
2  Patlu  [24.4]

In [ ]:
data =  {
    'Joe':[10,24,35],
     'harry':[20.00,45,50],
     'Patlu':[24.4,0.00,60]      
}
print(data )

t = pd.DataFrame(data).T
print(t)

{'Joe': [10, 24, 35], 'harry': [20.0, 45, 50], 'Patlu': [24.4, 0.0, 60]}
          0     1     2
Joe    10.0  24.0  35.0
harry  20.0  45.0  50.0
Patlu  24.4   0.0  60.0

In [62]:
students_info = {
    'Name': ['Harshit','alien','kansika'],
    'City':['Shahjahanpur','kanpur','Naubasta'],
    'Country': ['Kanpur','kannauj','america'],
    'Age': ['24','35','60']
}
df = pd.DataFrame.from_dict(
    students_info, 
    orient='index',
    columns=['Student1','Student2','Student3'])

df

             Student1 Student2  Student3
Name          Harshit    alien   kansika
City     Shahjahanpur   kanpur  Naubasta
Country        Kanpur  kannauj   america
Age                24       35        60