## PANDAS

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels = ['a','b','c','d']
list = [10,20,30,40]
arr = np.array([10,20,30])
dict = {'a':10,'b':20,'c':30}

In [13]:
pd.Series(list)

0    10
1    20
2    30
3    40
dtype: int64

In [14]:
pd.Series(list,index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [18]:
pd.Series(dict)

a    10
b    20
c    30
dtype: int64

## Creating a DataFrame
---
```python

In [5]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
col = ['name', 'Age','City','Sallary']
df2 = pd.DataFrame(data_list,columns=col)
df2

    name  Age      City  Sallary
0   John   28  New York    65000
1   Anna   34     Paris    70000
2  Peter   29    Berlin    62000
3  Linda   42    London    85000

In [53]:
df2['name']

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: object

In [36]:
df2[['name','City']]

    name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### Creating a new Column and adding to existing DataFrame
---

```python

In [12]:
df2["Designation"] =['Doctor','Teacher','lawyer','Engineer']

In [55]:
df2

    name  Age      City  Sallary Designation
0   John   28  New York    65000      Doctor
1   Anna   34     Paris    70000     Teacher
2  Peter   29    Berlin    62000      lawyer
3  Linda   42    London    85000    Engineer

### REMOVING A COLUMN
---

In [38]:
df2.drop('Age',axis=1)    #it show a snapshot after removing while actual data still remain in memoery

    name      City  Sallary Designation
0   John  New York    65000      Doctor
1   Anna     Paris    70000     Teacher
2  Peter    Berlin    62000      lawyer
3  Linda    London    85000    Engineer

In [49]:
df2    # here it shows the original data again

    name  Age      City  Sallary Designation
0   John   28  New York    65000      Doctor
1   Anna   34     Paris    70000     Teacher
2  Peter   29    Berlin    62000      lawyer
3  Linda   42    London    85000    Engineer

In [50]:
df2.drop(['Age','City'],axis=1,inplace=True)

In [51]:
df2

    name  Sallary Designation
0   John    65000      Doctor
1   Anna    70000     Teacher
2  Peter    62000      lawyer
3  Linda    85000    Engineer

### Selecting Rows
---

In [13]:
df2

    name  Age      City  Sallary Designation
0   John   28  New York    65000      Doctor
1   Anna   34     Paris    70000     Teacher
2  Peter   29    Berlin    62000      lawyer
3  Linda   42    London    85000    Engineer

In [14]:
df2.loc[3]

name              Linda
Age                  42
City             London
Sallary           85000
Designation    Engineer
Name: 3, dtype: object

In [59]:
df2.iloc[2]

name            Peter
Age                29
City           Berlin
Sallary         62000
Designation    lawyer
Name: 2, dtype: object

### Selecting Subsets of Rows and Columns
---

In [15]:
df2.loc[[0,1]][['City','Sallary']]

       City  Sallary
0  New York    65000
1     Paris    70000

In [63]:
df2.loc[[2,3]][['name','Age']]

    name  Age
2  Peter   29
3  Linda   42

### Conditional Selection
---

In [16]:
df2

    name  Age      City  Sallary Designation
0   John   28  New York    65000      Doctor
1   Anna   34     Paris    70000     Teacher
2  Peter   29    Berlin    62000      lawyer
3  Linda   42    London    85000    Engineer

In [17]:
df2[df2['Age']>30]

    name  Age    City  Sallary Designation
1   Anna   34   Paris    70000     Teacher
3  Linda   42  London    85000    Engineer

In [18]:
df2[(df2['Age']>30) & (df2['City']=='Paris')]

   name  Age   City  Sallary Designation
1  Anna   34  Paris    70000     Teacher

# MISSING DATA
---

In [19]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [20]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [74]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [21]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
# The any() method is used to check if there are any True values in the DataFrame.
# In this case, it will return True for each column that contains at least one NaN value, and False for columns that do not contain any NaN values.
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
# dropna() is a method in pandas that is used to remove missing values (NaN) from a DataFrame. 
# By default, it removes any row that contains at least one NaN value. You can also specify to drop columns 
# instead of rows by using the axis parameter.
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [22]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
#thresh parameter is used to specify the minimum number of non-NA values required to keep a row or column.
# In this case, thresh=3 means that a row will be dropped if it has less than 3 non-NA values.
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

### Filling the missing data with fillna() method
---

In [24]:
#fillna(value) is a method in pandas that is used to fill missing values (NaN) in a DataFrame with a specified value. 
# This can be useful for handling missing data and ensuring that your DataFrame does not contain any NaN values.
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [81]:
values= {'A' :0,'B':10,'C':50,'D':200}
df.fillna(value=values)

     A  B     C      D
0  1.0  1   1.0    1.0
1  2.0  2   2.0  200.0
2  0.0  3   3.0  200.0
3  4.0  4  50.0  200.0
4  5.0  5  50.0    5.0

In [82]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [83]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

## MERGE, JOIN AND CONCATENATE
---

In [25]:

employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [26]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [27]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [28]:
pd.merge(employees, salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [29]:
#inner join: This is the default join type. It returns only the rows that have matching values in both DataFrames based on the specified key column(s). 
# In this case, it will return only the employees who have a corresponding salary record in the salaries DataFrame.
pd.merge(employees,salaries,on='employee_id',how ='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [30]:
# outer join: This join type returns all rows from both DataFrames,
# and fills in NaN for missing matches on either side.
pd.merge(employees,salaries,on='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [31]:
# left join: This join type returns all rows from the left DataFrame (employees) and the matching rows from the right DataFrame (salaries). 
# If there is no match, the result will contain NaN for the columns from the right DataFrame.
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [32]:
#right join: This join type returns all rows from the right DataFrame (salaries) and the matching rows from the left DataFrame (employees). 
# If there is no match, the result will contain NaN for the columns from the left DataFrame.
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

### concatenation
---

In [33]:

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [34]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [35]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [37]:
pd.concat([df1,df2])   # it will concatenate the dataframes vertically

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [38]:
pd.concat([df1,df2],axis=1)   # it will concatenate the dataframes horizontally

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining two DataFrames**

In [39]:

df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [40]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [41]:
df2

   score
2     85
3     90
4     75

In [42]:

df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [43]:

df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

**grouping**

In [44]:

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [45]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [46]:
#grouping is a powerful operation in pandas that allows you to split your data into groups based on one or more columns, 
# and then apply a function to each group independently. This is often used for aggregation, transformation
cat = df.groupby('Category')
cat
for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [47]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [48]:
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [49]:
# group by multiple columns
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**AGGREGATION**
---
it is used to the following operations on data:
- sum()_______________  syntax: df['column_name'].sum()
- mean()_______________  syntax: df['column_name'].mean()
- std() _______________   syntax: df['column_name'].std()
- min() _______________   syntax: df['column_name'].min()
- max() _______________  syntax: df['column_name'].max()
- count() _______________  syntax: df['column_name'].count()

In [51]:
df['Sales'].mean()

np.float64(187.5)

In [53]:
df['Sales'].median()

np.float64(190.0)

In [55]:
df['Sales'].std()

np.float64(66.06274074155351)

In [56]:
df['Sales'].count()

np.int64(8)

In [58]:
df['Sales'].agg(['sum','mean','std','min','max','count'])

sum      1500.000000
mean      187.500000
std        66.062741
min       100.000000
max       300.000000
count       8.000000
Name: Sales, dtype: float64

**PIVOT TABLE**

In [59]:

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    775     42   John  January      Q1
1  2023-01-02       B   West    480     61   Mary  January      Q1
2  2023-01-03       C  North    743     31    Bob  January      Q1
3  2023-01-04       D  South    814     85  Alice  January      Q1
4  2023-01-05       A   East    926     52   John  January      Q1
5  2023-01-06       B   West    778     35   Mary  January      Q1
6  2023-01-07       C  North    963     64    Bob  January      Q1
7  2023-01-08       D  South    237     10  Alice  January      Q1
8  2023-01-09       A   East    272     94   John  January      Q1
9  2023-01-10       B   West    644     71   Mary  January      Q1
10 2023-01-11       C  North    752     71    Bob  January      Q1
11 2023-01-12       D  South    320     27  Alice  January      Q1
12 2023-01-13       A   East    360     78   John  January      Q1
13 2023-01-14       B   West    895     11   Mary  January      Q1
14 2023-01-15       C  North    394     71    Bob  January      Q1
15 2023-01-16       D  South    236     39  Alice  January      Q1
16 2023-01-17       A   East    151     31   John  January      Q1
17 2023-01-18       B   West    819     38   Mary  January      Q1
18 2023-01-19       C  North    985     23    Bob  January      Q1
19 2023-01-20       D  South    151     19  Alice  January      Q1

In [66]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='sum')

Product       A       B       C       D
Region
East     2484.0     NaN     NaN     NaN
North       NaN     NaN  3837.0     NaN
South       NaN     NaN     NaN  1758.0
West        NaN  3616.0     NaN     NaN

In [65]:
pi =pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product',aggfunc='sum')
pi

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     2484.0     NaN     NaN     NaN  297.0    NaN    NaN    NaN
North       NaN     NaN  3837.0     NaN    NaN    NaN  260.0    NaN
South       NaN     NaN     NaN  1758.0    NaN    NaN    NaN  180.0
West        NaN  3616.0     NaN     NaN    NaN  216.0    NaN    NaN

**Cross Tabulation**
---
the basic diffrence between pivot table and cross tabulation is that pivot table can take multiple aggregation function but cross tabulation can take only one aggregation function.

In [69]:
newdf =pd.crosstab(df['Region'],df['Product'])
newdf

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [70]:
newdf =pd.crosstab(df['Region'],df['Product'],values=df['Sales'],aggfunc='sum')
newdf

Product       A       B       C       D
Region
East     2484.0     NaN     NaN     NaN
North       NaN     NaN  3837.0     NaN
South       NaN     NaN     NaN  1758.0
West        NaN  3616.0     NaN     NaN